---
kind: pipeline
type: docker
name: buildd

steps:
- name: build-dd
  image: python
  commands:
  - python3 -m venv python-env
  - pwd
  - ls
  - sudo ./python-env/bin/activate
  - pip install datadog-checks-dev[cli]
  - ddev release build crest_data_systems_dell_emc_isilon
